version 0.0
os: linux
files: 
  - source: ./
    destination: /home/ubuntu/FILO_LISTEN_BOT
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - directory
      - file
